(define (problem BLOCKS-4-0)
(:domain BLOCKS)
(:objects A B C D E F - block)
(:INIT (CLEAR C) (CLEAR A) (CLEAR B) (CLEAR D) (ONTABLE C) (ONTABLE A)
 (ONTABLE B) (ONTABLE D) (HANDEMPTY))
(:goal (AND (ON F E) (ON E D) (ON D C) (ON C B) (ON B A)))
)